from enum import Enum


class UploadedTrackFieldKey(str, Enum):
    USER = "user"
    UUID = "uuid"
    CREATED_ON = "created_on"
    UPDATED_ON = "updated_on"
    PLAY_COUNT = "play_count"
    TRACK_FILE_INTERNAL = "track_file"
    TRACK_FILE_PUBLIC = "file"
    TRACK_FILE_FINGERPRINT_MUST_BE_UNIQUE = "track_file_fingerprint_must_be_unique"
    TITLE = "title"
    FILE = "file"
    ARTISTS = "artists"
    ALBUM = "album"
    TRACK_NUMBER = "track_number"
    GENRE = "genre"
    RATING = "rating"
    PLAYLISTS = "playlists"
    UPLOADED_TRACK_PLAYLIST_RELS = "uploaded_track_playlist_rels"
    LANGUAGE = "language"
    PLAYLISTS_PUBLIC = "playlists"
    ARCHIVED = "archived"
    RELATIVE_URL = "relative_url"
