services:
  api:
    volumes:
      - ./:/home/app/
    command: >-
      bash -lc "bash scripts/setup-filesystem.sh &&
      bash scripts/wait-for-postgres-db.sh db 5432 20 2 &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:${APP_PORT:-8000}"
