class Fields:
    FILE = "file"
    INCLUDE_MUSICBRAINZ_ANALYSIS = "include_musicbrainz_analysis"
    SESSION_TOKEN = "session_token"
    SESSION_EXPIRES_IN_SECONDS = "session_expires_in_seconds"
    TITLE = "title"
    ARTISTS_NAMES = "artists_names"
    ALBUM_NAME = "album_name"
    ALBUM_ARTISTS_NAMES = "album_artists_names"
    GENRES_NAMES = "genres_names"
    RATING = "rating"
    LANGUAGE = "language"
