# Generated by Django 5.2.8 on 2026-02-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_tmta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Designates a user as a system-owned account. Cannot log in.'),
        ),
    ]
