# Generated by Django 5.2.8 on 2026-02-06 06:42

import uuid

import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import the_music_tree_api_kit.field
import the_music_tree_api_kit.field.foreign_key.AppForeignKey
import the_music_tree_api_kit.field.foreign_key.AppManyToManyField
import the_music_tree_api_kit.field.foreign_key.AppOneToOneField
import the_music_tree_api_kit.field.foreign_key.PrivateForeignKey
import the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField
import the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField
from django.conf import settings
from django.db import migrations, models

import hear.model.utils.ConcatOp
import hear.model.utils.ConditionalExpression
import hear.model.utils.PreserveSpacesStorage
import hear.model.utils.utils
import hear.validator.TrackFileValidator


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("is_test_user", models.BooleanField(default=False)),
                (
                    "lib_path_relative_to_media",
                    models.GeneratedField(
                        db_persist=True,
                        expression=hear.model.utils.ConditionalExpression.ConditionalExpression(
                            condition_field="is_test_user",
                            output_field=the_music_tree_api_kit.field.AppCharField(max_length=256),
                            when_false=hear.model.utils.ConcatOp.ConcatOp(
                                models.Value("libraries"), models.Value("/"), models.Value("user_"), models.F("id")
                            ),
                            when_true=hear.model.utils.ConcatOp.ConcatOp(
                                models.Value("libraries"), models.Value("/"), models.Value("test_user_"), models.F("id")
                            ),
                        ),
                        output_field=the_music_tree_api_kit.field.AppCharField(max_length=256),
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "htmt_api_user",
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("play_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
                "db_table": "htmt_api_playlist",
            },
        ),
        migrations.CreateModel(
            name="MbRecordingMissingCauseCode",
            fields=[
                (
                    "code",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Audio Meta Amalysis Disabled"),
                            (1, "Track File Fingerprinting Failed"),
                            (2, "Duration Below Or Equal 1 Sec"),
                            (3, "Lookup Found No Matching Recording"),
                            (4, "Lookup Failed Due To Invalid Fingerprint"),
                            (5, "Lookup Failed With Internal Error"),
                            (6, "Lookup Failed With Unknown Response Error Code"),
                            (7, "Lookup Failed With Unknown Response Status Code"),
                            (8, "Lookup Failed Dns Resolution Error"),
                        ],
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("label", the_music_tree_api_kit.field.AppCharField(max_length=256, unique=True)),
            ],
            options={
                "verbose_name": "MusicBrainz Recording Missing Cause Code",
                "verbose_name_plural": "MusicBrainz Recording Missing Causes Codes",
                "db_table": "htmt_api_mb_recording_missing_cause_code",
            },
        ),
        migrations.CreateModel(
            name="SpotifyUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("spotify_id", models.CharField(max_length=255, unique=True)),
                ("spotify_access_token", models.TextField(blank=True, null=True)),
                ("spotify_refresh_token", models.TextField(blank=True, null=True)),
                ("spotify_profile", models.JSONField(blank=True, null=True)),
                ("spotify_token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "spotify_library_last_synced_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of when the user's Spotify library was last synced", null=True
                    ),
                ),
                (
                    "spotify_sync_in_progress",
                    models.BooleanField(
                        default=False, help_text="Indicates if a Spotify library sync is currently in progress"
                    ),
                ),
            ],
            options={
                "verbose_name": "Spotify User",
                "verbose_name_plural": "Spotify Users",
                "db_table": "htmt_api_spotify_user",
            },
            bases=("hear.user",),
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("_name", the_music_tree_api_kit.field.AppCharField(db_column="name", default=None, max_length=256)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "htmt_api_artist",
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("_name", the_music_tree_api_kit.field.AppCharField(db_column="name", default=None, max_length=256)),
                ("year", the_music_tree_api_kit.field.AppCharField(default=None, max_length=4, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "album_artists",
                    the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(
                        related_name="albums", to="hear.artist"
                    ),
                ),
            ],
            options={
                "db_table": "htmt_api_album",
            },
        ),
        migrations.CreateModel(
            name="Criteria",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("_name", the_music_tree_api_kit.field.AppCharField(db_column="name", max_length=256)),
                (
                    "parent",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="hear.criteria",
                    ),
                ),
                (
                    "root",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, related_name="descendants", to="hear.criteria"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Criteria",
                "verbose_name_plural": "Criterias",
                "db_table": "htmt_api_criteria",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[],
            options={
                "db_table": "htmt_api_genre",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("hear.criteria",),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[],
            options={
                "db_table": "htmt_api_tag",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("hear.criteria",),
        ),
        migrations.CreateModel(
            name="CriteriaLineageRel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("degree", models.PositiveIntegerField()),
                (
                    "ascendant",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="descendants_rels", to="hear.criteria"
                    ),
                ),
                (
                    "descendant",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ascendants_rels", to="hear.criteria"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Criteria Lineage Relation",
                "verbose_name_plural": "Criteria Lineage Relations",
                "db_table": "htmt_api_criteria_lineage_rel",
            },
        ),
        migrations.AddField(
            model_name="criteria",
            name="ascendants",
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(
                through="hear.CriteriaLineageRel", through_fields=("descendant", "ascendant"), to="hear.criteria"
            ),
        ),
        migrations.CreateModel(
            name="CriteriaPlaylist",
            fields=[
                (
                    "playlist",
                    the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="criteria_playlist",
                        serialize=False,
                        to="hear.playlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Criteria Playlist",
                "verbose_name_plural": "Criteria Playlists",
                "db_table": "htmt_api_criteria_playlist",
            },
            bases=("hear.playlist",),
        ),
        migrations.CreateModel(
            name="ManualPlaylist",
            fields=[
                (
                    "playlist",
                    the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="manual_playlist",
                        serialize=False,
                        to="hear.playlist",
                    ),
                ),
                ("_name", the_music_tree_api_kit.field.AppCharField(db_column="name", max_length=256)),
            ],
            options={
                "verbose_name": "Manual Playlist",
                "verbose_name_plural": "Manual Playlists",
                "db_table": "htmt_api_manual_playlist",
            },
            bases=("hear.playlist",),
        ),
        migrations.CreateModel(
            name="CriteriaType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", the_music_tree_api_kit.field.AppCharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Criteria Type",
                "verbose_name_plural": "Criteria Types",
                "db_table": "htmt_api_criteria_type",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("label", ""), _negated=True), name="criteria_non_empty_label"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="criteria",
            name="type",
            field=the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hear.criteriatype"
            ),
        ),
        migrations.CreateModel(
            name="FingerprintMissingCauseCode",
            fields=[
                (
                    "code",
                    models.IntegerField(
                        choices=[
                            (0, "Audio Meta Amalysis Disabled"),
                            (1, "Service Not Found"),
                            (2, "Fpcalc Error With Status 2"),
                            (3, "Wrong File Extension"),
                            (4, "Wrong File Type"),
                            (5, "File Not Found In Pool"),
                            (6, "Unknown Bad Request"),
                            (7, "Internal Error"),
                            (8, "Timeout Error"),
                            (9, "Unknown Connexion Error"),
                            (10, "Unknown Unprocessable Entity Error"),
                        ],
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("label", the_music_tree_api_kit.field.AppCharField(max_length=256, unique=True)),
            ],
            options={
                "verbose_name": "Fingerprinting Error Code",
                "verbose_name_plural": "Fingerprinting Error Codes",
                "db_table": "htmt_api_fingerprint_missing_cause_code",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("label", ""), _negated=True),
                        name="fingerprint_missing_cause_non_empty_label",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FingerprintMissingCause",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("message", the_music_tree_api_kit.field.AppCharField(max_length=256, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "code",
                    the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="hear.fingerprintmissingcausecode"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fingerprinting Error",
                "verbose_name_plural": "Fingerprinting Errors",
                "db_table": "htmt_api_fingerprint_missing_cause",
            },
        ),
        migrations.CreateModel(
            name="MbArtist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("musicbrainz_id", the_music_tree_api_kit.field.AppCharField(max_length=36, unique=True)),
                (
                    "musicbrainz_link",
                    models.GeneratedField(
                        db_persist=True,
                        expression=hear.model.utils.ConcatOp.ConcatOp(
                            models.Value("https://musicbrainz.org/artist/"), models.F("musicbrainz_id")
                        ),
                        output_field=the_music_tree_api_kit.field.AppCharField(max_length=70),
                    ),
                ),
                ("name", the_music_tree_api_kit.field.AppCharField(default=None, max_length=256)),
            ],
            options={
                "verbose_name": "Musicbrainz Artist",
                "verbose_name_plural": "Musicbrainz Artists",
                "db_table": "htmt_api_mb_artist",
                "indexes": [models.Index(fields=["musicbrainz_id"], name="mb_artist_id_idx")],
            },
        ),
        migrations.CreateModel(
            name="MbRecording",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("musicbrainz_id", the_music_tree_api_kit.field.AppCharField(max_length=36, unique=True)),
                (
                    "musicbrainz_link",
                    models.GeneratedField(
                        db_persist=True,
                        expression=hear.model.utils.ConcatOp.ConcatOp(
                            models.Value("https://musicbrainz.org/recording/"), models.F("musicbrainz_id")
                        ),
                        output_field=the_music_tree_api_kit.field.AppCharField(max_length=70),
                    ),
                ),
                ("title", the_music_tree_api_kit.field.AppCharField(editable=False, max_length=256)),
                ("score", models.DecimalField(decimal_places=8, editable=False, max_digits=9)),
                ("duration_in_sec", models.IntegerField(editable=False, null=True)),
                ("release_date", models.DateField(blank=True, editable=False, null=True)),
                (
                    "musicbrainz_artists",
                    the_music_tree_api_kit.field.foreign_key.AppManyToManyField.AppManyToManyField(to="hear.mbartist"),
                ),
            ],
            options={
                "verbose_name": "MusicBrainz Recording",
                "verbose_name_plural": "MusicBrainz Recordings",
                "db_table": "htmt_api_mb_recording",
            },
        ),
        migrations.CreateModel(
            name="MbRecordingMissingCause",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("message", the_music_tree_api_kit.field.AppCharField(max_length=400, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "code",
                    the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="hear.mbrecordingmissingcausecode"
                    ),
                ),
            ],
            options={
                "verbose_name": "MusicBrainz Recording Missing Cause",
                "verbose_name_plural": "MusicBrainz Recording Missing Causes",
                "db_table": "htmt_api_mb_recording_missing_cause",
            },
        ),
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("content_uuid", models.UUIDField(db_column="object_pk")),
                (
                    "content_type",
                    the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Play",
                "verbose_name_plural": "Plays",
                "db_table": "htmt_api_play",
            },
        ),
        migrations.CreateModel(
            name="SpotifyArtist",
            fields=[
                (
                    "spotify_id",
                    the_music_tree_api_kit.field.AppCharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", the_music_tree_api_kit.field.AppCharField(editable=False, max_length=256)),
                ("popularity", models.IntegerField(editable=False, null=True)),
                (
                    "spotify_link",
                    models.GeneratedField(
                        db_persist=True,
                        expression=hear.model.utils.ConcatOp.ConcatOp(
                            models.Value("https://open.spotify.com/artist/"), models.F("spotify_id")
                        ),
                        output_field=the_music_tree_api_kit.field.AppCharField(max_length=500),
                    ),
                ),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100), editable=False, null=True, size=None
                    ),
                ),
                ("images", models.JSONField(editable=False, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Spotify Artist",
                "verbose_name_plural": "Spotify Artists",
                "db_table": "htmt_api_spotify_artist",
                "indexes": [models.Index(fields=["spotify_id"], name="sp_artist_id_idx")],
            },
        ),
        migrations.CreateModel(
            name="SpotifyLibTrack",
            fields=[
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                (
                    "spotify_id",
                    the_music_tree_api_kit.field.AppCharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", the_music_tree_api_kit.field.AppCharField(db_column="name", editable=False, max_length=256)),
                ("duration_ms", models.IntegerField(db_column="duration_ms", editable=False)),
                ("popularity", models.IntegerField(db_column="popularity", editable=False, null=True)),
                (
                    "spotify_link",
                    models.GeneratedField(
                        db_column="spotify_link",
                        db_persist=True,
                        expression=hear.model.utils.ConcatOp.ConcatOp(
                            models.Value("https://open.spotify.com/track/"), models.F("spotify_id")
                        ),
                        output_field=the_music_tree_api_kit.field.AppCharField(max_length=500),
                    ),
                ),
                ("album", models.JSONField(db_column="album", editable=False, null=True)),
                (
                    "preview_url",
                    models.URLField(blank=True, db_column="preview_url", editable=False, max_length=512, null=True),
                ),
                ("explicit", models.BooleanField(db_column="explicit", default=False, editable=False)),
                ("last_synced_at", models.DateTimeField(db_column="last_synced_at", editable=False, null=True)),
                (
                    "is_removed",
                    models.BooleanField(
                        db_column="is_removed",
                        default=False,
                        editable=False,
                        help_text="Indicates if the track has been removed from Spotify",
                    ),
                ),
                ("followers", models.IntegerField(db_column="followers", editable=False, null=True)),
                ("href", models.URLField(blank=True, db_column="href", editable=False, max_length=512, null=True)),
                (
                    "type",
                    the_music_tree_api_kit.field.AppCharField(
                        db_column="type", editable=False, max_length=50, null=True
                    ),
                ),
                (
                    "uri",
                    the_music_tree_api_kit.field.AppCharField(
                        db_column="uri", editable=False, max_length=256, null=True
                    ),
                ),
                (
                    "spotify_artists",
                    the_music_tree_api_kit.field.foreign_key.AppManyToManyField.AppManyToManyField(
                        db_column="spotify_artists", to="hear.spotifyartist"
                    ),
                ),
            ],
            options={
                "verbose_name": "Spotify Library Track",
                "verbose_name_plural": "Spotify Library Tracks",
                "db_table": "htmt_api_spotify_lib_track",
            },
        ),
        migrations.CreateModel(
            name="UploadedTrack",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("play_count", models.PositiveIntegerField(default=0)),
                ("title", the_music_tree_api_kit.field.AppCharField(max_length=256)),
                ("track_file_fingerprint_must_be_unique", models.BooleanField(default=False)),
                (
                    "track_number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "language",
                    the_music_tree_api_kit.field.AppCharField(blank=True, default=None, max_length=3, null=True),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "album",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_tracks_of_album",
                        to="hear.album",
                    ),
                ),
                (
                    "artists",
                    the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(
                        blank=True, related_name="uploaded_tracks_of_artist", to="hear.artist"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded Track",
                "verbose_name_plural": "Uploaded Tracks",
                "db_table": "htmt_api_uploaded_track",
            },
        ),
        migrations.CreateModel(
            name="TrackFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                (
                    "file",
                    models.FileField(
                        help_text="Only audio formats accepted.",
                        max_length=256,
                        storage=hear.model.utils.PreserveSpacesStorage.PreserveSpacesStorage(),
                        upload_to=hear.model.utils.utils.get_user_lib_path,
                        validators=[hear.validator.TrackFileValidator.TrackFileValidator()],
                    ),
                ),
                ("duration_in_sec", models.PositiveIntegerField()),
                ("fingerprint_memory", models.BinaryField(blank=True, default=None, editable=True, null=True)),
                ("md5_has_been_corrected", models.BooleanField(default=False)),
                ("size_in_bytes", models.DecimalField(decimal_places=2, max_digits=11)),
                (
                    "size_in_ko",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("size_in_bytes"), "/", models.Value(1024)
                        ),
                        output_field=models.DecimalField(decimal_places=2, max_digits=8),
                    ),
                ),
                (
                    "size_in_mo",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            models.F("size_in_bytes"), "/", models.Value(1048576)
                        ),
                        output_field=models.DecimalField(decimal_places=2, max_digits=5),
                    ),
                ),
                ("bitrate_in_kbps", models.IntegerField()),
                (
                    "fingerprint_missing_cause",
                    the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="hear.fingerprintmissingcause",
                    ),
                ),
                (
                    "musicbrainz_recording",
                    the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(
                        default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="hear.mbrecording"
                    ),
                ),
                (
                    "musicbrainz_recording_missing_cause",
                    the_music_tree_api_kit.field.foreign_key.AppOneToOneField.AppOneToOneField(
                        null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="hear.mbrecordingmissingcause"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_track",
                    the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="track_file", to="hear.uploadedtrack"
                    ),
                ),
            ],
            options={
                "verbose_name": "Track File",
                "verbose_name_plural": "Track Files",
                "db_table": "htmt_api_track_file",
            },
        ),
        migrations.CreateModel(
            name="UploadedTrackPlaylistRel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "playlist",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_track_playlist_rels",
                        to="hear.playlist",
                    ),
                ),
                (
                    "uploaded_track",
                    the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_track_playlist_rels",
                        to="hear.uploadedtrack",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded Track Playlist Relation",
                "verbose_name_plural": "Uploaded Track Playlist Relations",
                "db_table": "htmt_api_uploaded_track_playlist_rel",
            },
        ),
        migrations.AddField(
            model_name="uploadedtrack",
            name="playlists",
            field=the_music_tree_api_kit.field.foreign_key.PrivateManyToManyField.PrivateManyToManyField(
                related_name="uploaded_tracks_of_playlist", through="hear.UploadedTrackPlaylistRel", to="hear.playlist"
            ),
        ),
        migrations.CreateModel(
            name="AllUploadedTracksMixin",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_on", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "All Uploaded Tracks Mixin",
                "verbose_name_plural": "All Uploaded Tracks Mixins",
                "db_table": "htmt_api_all_uploaded_tracks_mixin",
                "constraints": [models.UniqueConstraint(fields=("user",), name="unique_user_all_tracks_mixin")],
            },
        ),
        migrations.AddConstraint(
            model_name="artist",
            constraint=models.CheckConstraint(
                condition=models.Q(("_name", ""), _negated=True), name="artist_non_empty_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.CheckConstraint(
                condition=models.Q(("_name", ""), _negated=True), name="album_non_empty_name"
            ),
        ),
        migrations.AddField(
            model_name="uploadedtrack",
            name="genre",
            field=the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="uploaded_tracks_of_criteria",
                to="hear.genre",
            ),
        ),
        migrations.AddIndex(
            model_name="criterialineagerel",
            index=models.Index(fields=["user"], name="crit_lineage_rel_user_idx"),
        ),
        migrations.AddField(
            model_name="criteriaplaylist",
            name="criteria",
            field=the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria_playlist",
                to="hear.criteria",
            ),
        ),
        migrations.AddField(
            model_name="criteriaplaylist",
            name="parent",
            field=the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="hear.criteriaplaylist",
            ),
        ),
        migrations.AddField(
            model_name="criteriaplaylist",
            name="root",
            field=the_music_tree_api_kit.field.foreign_key.PrivateForeignKey.PrivateForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="root_descendants",
                to="hear.criteriaplaylist",
            ),
        ),
        migrations.AddField(
            model_name="criteriaplaylist",
            name="type",
            field=the_music_tree_api_kit.field.foreign_key.AppForeignKey.AppForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hear.criteriatype"
            ),
        ),
        migrations.CreateModel(
            name="GenrePlaylist",
            fields=[],
            options={
                "db_table": "htmt_api_genre_playlist",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("hear.criteriaplaylist",),
        ),
        migrations.CreateModel(
            name="TagPlaylist",
            fields=[],
            options={
                "db_table": "htmt_api_tag_playlist",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("hear.criteriaplaylist",),
        ),
        migrations.AddIndex(
            model_name="manualplaylist",
            index=models.Index(fields=["_name"], name="manual_playlist_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="manualplaylist",
            constraint=models.CheckConstraint(
                condition=models.Q(("_name", ""), _negated=True), name="manual_playlist_non_empty_name"
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(fields=["user", "uuid"], name="playlist_user_uuid_idx"),
        ),
        migrations.AddIndex(
            model_name="criteria",
            index=models.Index(fields=["user", "_name"], name="criteria_user_name_idx"),
        ),
        migrations.AddIndex(
            model_name="criteria",
            index=models.Index(fields=["user", "uuid"], name="criteria_user_uuid_idx"),
        ),
        migrations.AddConstraint(
            model_name="criteria",
            constraint=models.CheckConstraint(
                condition=models.Q(("_name", ""), _negated=True), name="criteria_non_empty_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="criteria",
            constraint=models.UniqueConstraint(fields=("user", "_name"), name="unique_name_per_user"),
        ),
        migrations.AddIndex(
            model_name="mbrecording",
            index=models.Index(fields=["musicbrainz_id"], name="mb_recording_id_idx"),
        ),
        migrations.AddIndex(
            model_name="play",
            index=models.Index(fields=["user", "content_type", "content_uuid"], name="htmt_api_pl_user_id_5fae83_idx"),
        ),
        migrations.AddIndex(
            model_name="spotifylibtrack",
            index=models.Index(fields=["spotify_id"], name="sp_track_id_idx"),
        ),
        migrations.AddIndex(
            model_name="uploadedtrackplaylistrel",
            index=models.Index(fields=["user", "playlist"], name="htmt_api_up_user_id_29ec5b_idx"),
        ),
        migrations.AddIndex(
            model_name="uploadedtrackplaylistrel",
            index=models.Index(fields=["user", "uploaded_track"], name="htmt_api_up_user_id_6ab4bf_idx"),
        ),
        migrations.AddIndex(
            model_name="uploadedtrack",
            index=models.Index(fields=["user", "title"], name="htmt_api_up_user_id_d37215_idx"),
        ),
        migrations.AddIndex(
            model_name="uploadedtrack",
            index=models.Index(fields=["user", "genre"], name="htmt_api_up_user_id_765763_idx"),
        ),
        migrations.AddIndex(
            model_name="uploadedtrack",
            index=models.Index(fields=["user", "album"], name="htmt_api_up_user_id_f43f35_idx"),
        ),
        migrations.AddIndex(
            model_name="criteriaplaylist",
            index=models.Index(fields=["criteria"], name="crit_playlist_criteria_idx"),
        ),
    ]
