# Generated by Django 5.2.8 on 2026-08-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hear", "0017_reparent_uploaded_track_and_playlists_onto_genre_kit"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteria",
            name="side",
            field=models.CharField(
                blank=True, choices=[("core", "Core"), ("pop", "Pop")], db_column="side", max_length=4, null=True
            ),
        ),
    ]
