# Hand-authored: repoints `side` from the shared `Criteria` table onto a new, real MTI
# `Genre` subtype (`the-music-tree-genre-kit` v0.14.0 -- see `AbstractGenreCriteria`).
# `Genre` used to be a `Criteria` proxy sharing the `htmt_api_criteria` table exactly,
# hence `side` living there; it is now a genuine child table (`htmt_api_genre`) that
# owns `side`.
#
# Can't be autogenerated as a single `RemoveField`/`CreateModel` pair: Django's migration
# state renderer builds each model class eagerly as operations are applied, and a `Genre`
# MTI child declaring its own `side` field clashes with `Criteria` (its base) still
# declaring `side` too -- the two can never coexist in state, in either order. So the
# `RemoveField` is split via `SeparateDatabaseAndState`: its *state* half runs first
# (state-only, so `Genre` can be created inheriting no `side` from `Criteria` without a
# clash) while its *database* half runs last, after the data migration has copied
# `side` off the still-physically-present `htmt_api_criteria.side` column onto the new
# `htmt_api_genre` rows -- read via raw SQL since the ORM's historical `Criteria` model
# no longer exposes that column once its state half has run.
import django.db.models.deletion
import the_music_tree_api_kit.field
import the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField
from django.db import migrations, models
from the_music_tree_genre_kit.criteria.type.CriteriaTypePks import CriteriaTypePks


def copy_side_to_genre(apps, schema_editor):
    Genre = apps.get_model("hear", "Genre")

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT uuid, side FROM htmt_api_criteria WHERE type_id = %s", [int(CriteriaTypePks.GENRE)])
        genre_side_by_criteria_uuid = cursor.fetchall()

    # `bulk_create` doesn't support multi-table-inherited models (it would need to insert
    # into both `htmt_api_criteria` and `htmt_api_genre`, but the parent row already exists here).
    for criteria_uuid, side in genre_side_by_criteria_uuid:
        Genre(criteria_ptr_id=criteria_uuid, side=side).save_base(raw=True, force_insert=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("hear", "0019_alter_criteria_side"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="criteria",
                    name="side",
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "criteria_ptr",
                    the_music_tree_api_kit.field.foreign_key.PrivateOneToOneField.PrivateOneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="genre",
                        serialize=False,
                        to="hear.criteria",
                    ),
                ),
                (
                    "side",
                    the_music_tree_api_kit.field.AppCharField(
                        blank=True,
                        choices=[("core", "Core"), ("pop", "Pop")],
                        db_column="side",
                        max_length=4,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "htmt_api_genre",
            },
            bases=("hear.criteria", models.Model),
        ),
        migrations.RunPython(copy_side_to_genre, noop_reverse),
        # Plain `RemoveField` can't be used here: its `state_forwards` unconditionally
        # tries to drop `side` from the accumulated project state too, but that already
        # happened above -- it would raise `KeyError` looking for a field that's already
        # gone. The column itself, though, is still physically present on
        # `htmt_api_criteria` (its state-only removal above didn't touch the database),
        # so drop it with raw SQL instead, once the data migration has finished reading
        # from it.
        migrations.RunSQL(
            sql="ALTER TABLE htmt_api_criteria DROP COLUMN side;",
            reverse_sql="ALTER TABLE htmt_api_criteria ADD COLUMN side varchar(4) NULL;",
        ),
    ]
