# Generated by Django 5.2.8 on 2026-09-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hear", "0020_genre_mti"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteria",
            name="summary",
            field=models.TextField(blank=True, db_column="summary", null=True),
        ),
    ]
