# Generated by Django 5.2.8 on 2026-09-25 12:47

import the_music_tree_api_kit.field
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hear", "0021_criteria_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="is_excluded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="genre",
            name="is_manually_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="genre",
            name="wikidata_id",
            field=the_music_tree_api_kit.field.AppCharField(
                blank=True, db_column="wikidata_id", max_length=32, null=True
            ),
        ),
    ]
