# Generated by Django 5.2.8 on 2026-09-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    # Archiving moved from the kit Track into hear: copy the values before the kit drops its column.
    run_before = [
        ('the_music_tree_genre_kit', '0008_remove_track_archived'),
    ]

    dependencies = [
        ('hear', '0025_criteria_case_insensitive_unique_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='has_name_conflict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedtrack',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE htmt_api_uploaded_track u SET archived = t.archived "
                "FROM the_music_tree_genre_kit_track t WHERE u.track_id = t.id"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
