# Generated by Django 5.2.8 on 2026-09-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hear", "0027_uploaded_track_archived_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="is_unaccepted_root",
            field=models.BooleanField(default=False),
        ),
    ]
