from hear.serializer.model.playlist.base.output.Fields import Fields as PlayListFields


class Fields:
    UUID = PlayListFields.UUID
    NAME = PlayListFields.NAME
    CREATED_ON = PlayListFields.CREATED_ON
    UPDATED_ON = PlayListFields.UPDATED_ON
    UPLOADED_TRACKS_NOT_ARCHIVED_PUBLIC = PlayListFields.UPLOADED_TRACKS_NOT_ARCHIVED_PUBLIC
    UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_PUBLIC = PlayListFields.UPLOADED_TRACKS_NOT_ARCHIVED_COUNT_PUBLIC
    UPLOADED_TRACKS_ARCHIVED_COUNT_PUBLIC = PlayListFields.UPLOADED_TRACKS_ARCHIVED_COUNT_PUBLIC
    DURATION_IN_SEC = PlayListFields.DURATION_IN_SEC
    DURATION_STR_IN_HOUR_MIN_SEC = PlayListFields.DURATION_STR_IN_HOUR_MIN_SEC
