name: Publish

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - chore/fix-cicd-to-o2switch-server
    tags:
      - 'v*'

jobs:
  static:
    name: Static files
    uses: ./.github/workflows/static-files.yml

  build:
    name: Docker image
    needs: [static]
    uses: ./.github/workflows/build.yml
    with:
      commit_hash: ${{ needs.static.outputs.collect_static_files_commit_hash }}
    secrets: inherit

  deploy:
    name: Deploy
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

